# Generated by Django 3.2 on 2021-04-19 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crmfood_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='waiterid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiterid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealstoorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmfood_app.order'),
        ),
        migrations.AddField(
            model_name='meals',
            name='categoryid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='crmfood_app.mealcategories'),
        ),
        migrations.AddField(
            model_name='mealcategories',
            name='departmentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmfood_app.departments'),
        ),
        migrations.AddField(
            model_name='checks',
            name='meals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='crmfood_app.meals'),
        ),
        migrations.AddField(
            model_name='checks',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='crmfood_app.order'),
        ),
    ]
