# Generated by Django 3.2 on 2021-06-17 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmfood_app', '0004_statuses_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statuses',
            old_name='user_id',
            new_name='user',
        ),
    ]
